// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

const databaseUrl =
	process.env.PRISMA_DATABASE_URL ?? process.env.DATABASE_URL
const directUrl =
	process.env.DIRECT_URL ?? process.env.POSTGRES_URL ?? process.env.DATABASE_URL

const isAccelerateUrl =
	typeof databaseUrl === "string" && databaseUrl.startsWith("prisma+postgres://")

if (!databaseUrl) {
	throw new Error("Missing DATABASE_URL or PRISMA_DATABASE_URL.")
}

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: isAccelerateUrl && directUrl ? directUrl : databaseUrl,
		...(directUrl ? { directUrl } : {}),
	},
})
